CREATE TABLE loving_families (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name varchar(200)
);

CREATE TABLE fuzzy_bunnies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  family_id bigint NOT NULL REFERENCES loving_families(id) NOT NULL,
  user_id uuid NOT NULL REFERENCES users(id) DEFAULT uid() NOT NULL,
  name varchar(200)
);

INSERT INTO loving_families (name)
VALUES 
  ('The Zhang Family'),
  ('the Garcia family'),
  ('the Silva family'),
  ('the Johnson family'),
  ('the the Ivanova family')
;